"""add_video_columns_and_jobs

Revision ID: 2b664509a956
Revises: 20260221_0001
Create Date: 2026-02-22 16:59:25.511556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b664509a956'
down_revision: Union[str, None] = '20260221_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('veo_operation_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('variation_number', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('generation_time_seconds', sa.Integer(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('detected_media_type', sa.String(length=10), nullable=True))
    op.add_column('posts', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('video_style_brief', sa.JSON(), nullable=True))
    op.add_column('posts', sa.Column('video_type', sa.String(length=20), nullable=True))
    op.add_column('posts', sa.Column('start_frame_url', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('video_duration', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('thumb_offset_ms', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_products_product_code'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=False)
    op.create_unique_constraint(op.f('uq_products_product_code'), 'products', ['product_code'])
    op.drop_column('posts', 'thumb_offset_ms')
    op.drop_column('posts', 'video_duration')
    op.drop_column('posts', 'start_frame_url')
    op.drop_column('posts', 'video_type')
    op.drop_column('posts', 'video_style_brief')
    op.drop_column('posts', 'video_url')
    op.drop_column('posts', 'detected_media_type')
    op.drop_table('video_jobs')
    # ### end Alembic commands ###
